language: generic 
sudo: required

services:
  - docker


before_install:
  - docker build -t martin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true martin/docker-react npm run test
